name       : pymarkups
version    : 3.1.0
release    : 6
source     :
    - https://github.com/retext-project/pymarkups/archive/3.1.0.tar.gz : e5ddd9215d76fa429c3c65fbded20b9e205040047aadce42e41e736775f82d0a
homepage   : https://github.com/retext-project/pymarkups
license    : BSD-3-Clause
component  : programming.python
summary    : Wrapper around various text markups
description: |
    This module provides a wrapper around various text markup languages. Available by default are Markdown, reStructuredText and Textile, but you can easily add your own markups.
builddeps  :
    - pygments
    - python-importlib-metadata
    - python-markdown-math
rundeps    :
    - python-importlib-metadata
    - python-markdown-math
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
