name       : pymarkups
version    : 2.0.0
release    : 2
source     :
    - https://github.com/retext-project/pymarkups/archive/2.0.0.tar.gz : 0d1ac398ecde6ec3904ec842abee7538d58a3a2d51ac2e61584a822dc6d73a06
license    : BSD-3-Clause
component  : programming.python
summary    : Wrapper around various text markups
description: |
    This module provides a wrapper around various text markup languages.
    Available by default are Markdown, reStructuredText and Textile, but you can easily add your own markups.
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
