name       : pymarkups
version    : 3.0.0
release    : 3
source     :
    - https://github.com/retext-project/pymarkups/archive/3.0.0.tar.gz : 5edc73ceed7d5ee207c481cc67852b5e54c731d65a32cb06afc27c455d5e70f4
license    : BSD-3-Clause
component  : programming.python
summary    : Wrapper around various text markups
description: |
    This module provides a wrapper around various text markup languages.
    Available by default are Markdown, reStructuredText and Textile, but you can easily add your own markups.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
