name       : pymarkups
version    : 3.0.0
release    : 5
source     :
    - https://github.com/retext-project/pymarkups/archive/3.0.0.tar.gz : 5edc73ceed7d5ee207c481cc67852b5e54c731d65a32cb06afc27c455d5e70f4
homepage   : https://github.com/retext-project/pymarkups
license    : BSD-3-Clause
component  : programming.python
summary    : Wrapper around various text markups
description: |
    This module provides a wrapper around various text markup languages.
    Available by default are Markdown, reStructuredText and Textile, but you can easily add your own markups.
builddeps  :
    - python-markdown-math
rundeps    :
    - python-markdown-math
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
