name       : pymarkups
version    : 4.0.0
release    : 13
source     :
    - https://github.com/retext-project/pymarkups/archive/refs/tags/4.0.0.tar.gz : 503e5a13b0a6c00b154291c751dc65b7176f10cf1c397120e935eb0562600811
homepage   : https://github.com/retext-project/pymarkups
license    : BSD-3-Clause
component  : programming.python
summary    : Wrapper around various text markups
description: |
    This module provides a wrapper around various text markup languages. Available by default are Markdown, reStructuredText and Textile, but you can easily add your own markups.
builddeps  :
    - python-build
    - python-docutils      # check
    - python-installer
    - python-markdown-math # check
    - python-packaging
    - python-pytest        # check
    - python-wheel
    - pygments             # check
rundeps    :
    - python-markdown-math
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
