name       : pymarkups
version    : 3.1.3
release    : 11
source     :
    - https://github.com/retext-project/pymarkups/archive/refs/tags/3.1.3.tar.gz : c6982db63675313464fe00bb9c35ae98dc0a20c59ecb387d19cfeb6f427cee10
homepage   : https://github.com/retext-project/pymarkups
license    : BSD-3-Clause
component  : programming.python
summary    : Wrapper around various text markups
description: |
    This module provides a wrapper around various text markup languages. Available by default are Markdown, reStructuredText and Textile, but you can easily add your own markups.
builddeps  :
    - pygments
    - python-markdown-math
rundeps    :
    - python-markdown-math
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
