name       : pymarkups
version    : 3.1.1
release    : 7
source     :
    - https://github.com/retext-project/pymarkups/archive/refs/tags/3.1.1.tar.gz : 62055078b8e10fbe6470e9cf57aa40299462c87102649817d26ae6c5d4831505
homepage   : https://github.com/retext-project/pymarkups
license    : BSD-3-Clause
component  : programming.python
summary    : Wrapper around various text markups
description: |
    This module provides a wrapper around various text markup languages. Available by default are Markdown, reStructuredText and Textile, but you can easily add your own markups.
builddeps  :
    - pygments
    - python-importlib-metadata
    - python-markdown-math
rundeps    :
    - python-importlib-metadata
    - python-markdown-math
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
