name       : pymarkups
version    : 3.1.2
release    : 10
source     :
    - https://github.com/retext-project/pymarkups/archive/refs/tags/3.1.2.tar.gz : 011df506e3f6a3afbf0294771ba025fc36f1969d7c4290cbdc71c437e9928afd
homepage   : https://github.com/retext-project/pymarkups
license    : BSD-3-Clause
component  : programming.python
summary    : Wrapper around various text markups
description: |
    This module provides a wrapper around various text markup languages. Available by default are Markdown, reStructuredText and Textile, but you can easily add your own markups.
builddeps  :
    - pygments
    - python-markdown-math
rundeps    :
    - python-markdown-math
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
